package pki

import (
	"context"
	"crypto/x509"
	"errors"
	"net/http"
	"os"
	"os/exec"
	"strings"
	"testing"
	"time"
)

// caURLEnvVar names the environment variable that points this test at a
// real Certificate-Authority instance (e.g. the certificate-authority
// service in deployments/compose/certificate-authority.yml). docs/Test_Plan.md §4
// requires unit tests to run with no external dependency and no Docker —
// same env-var-gated-skip pattern already used by
// services/database-vault/internal/storage/postgres_test.go's
// TestSaveUser_Postgres — so this test is skipped whenever the variable
// is unset, instead of being a hard dependency of `go test ./...`.
const caURLEnvVar = "PKI_TEST_CA_URL"

// caContainerEnvVar optionally overrides the Docker container name this
// test execs into to generate a real bootstrap token (see
// generateTestToken below). Defaults to defaultCAContainer, the plain,
// stable `container_name:` deployments/compose/certificate-authority.yml
// sets explicitly (not a Compose-project-derived name) — the only
// compose convention this project has for running the CA locally.
const caContainerEnvVar = "PKI_TEST_CA_CONTAINER"

const defaultCAContainer = "certificate-authority"

// Paths inside the certificate-authority container, fixed by this
// project's own deployments/compose/certificate-authority.yml (root cert location is
// smallstep/step-ca's own convention; the password file path is this
// compose file's chosen mount point for the dev-only secret in
// third-party/certificate-authority/config/password.dev-only.txt).
const (
	containerRootCert     = "/home/step/certs/root_ca.crt"
	containerPasswordFile = "/run/secrets/ca-password.dev-only" //nolint:gosec // a file path, not a credential value
)

// caName must match DOCKER_STEPCA_INIT_NAME in
// deployments/compose/certificate-authority.yml — used to confirm a certificate
// handed back by NewServer/NewClient really chains to this dev CA, not
// some other trust root.
const caName = "RAM-USB Dev CA"

// generateTestToken shells into the running certificate-authority
// container and runs `step ca token`, using the same admin JWK
// provisioner and dev-only password file
// (deployments/compose/certificate-authority.yml, DOCKER_STEPCA_INIT_PASSWORD_FILE)
// that container bootstrapped itself with. This generates a real,
// single-use bootstrap token end to end — no token is hand-crafted or
// stubbed. subject is an arbitrary identifier for the requesting
// service, analogous to what a real RAM-USB service would pass as its
// own name.
func generateTestToken(t *testing.T, caURL, container, subject string) string {
	t.Helper()

	if _, err := exec.LookPath("docker"); err != nil {
		t.Skipf("docker CLI not available: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	//nolint:gosec // container/caURL/subject come from this test's own env-gated
	// config and call sites, not untrusted request input (same justification
	// category as main.go's loadCertPool G304 suppression).
	cmd := exec.CommandContext(ctx, "docker", "exec", container,
		"step", "ca", "token", subject,
		"--ca-url", caURL,
		"--root", containerRootCert,
		"--provisioner", "admin",
		"--password-file", containerPasswordFile,
	)
	out, err := cmd.Output()
	if err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			t.Fatalf("docker exec %s step ca token: %v\nstderr: %s", container, err, exitErr.Stderr)
		}
		t.Fatalf("docker exec %s step ca token: %v", container, err)
	}

	return strings.TrimSpace(string(out))
}

func skipUnlessCAConfigured(t *testing.T) (caURL, container string) {
	t.Helper()

	caURL = os.Getenv(caURLEnvVar)
	if caURL == "" {
		t.Skipf("%s not set; skipping the real-Certificate-Authority CA-F-04/PKI-F-01 test. "+
			"Start deployments/compose/certificate-authority.yml's certificate-authority service "+
			"(docker compose -f deployments/compose/certificate-authority.yml up -d certificate-authority) "+
			"and set this variable (e.g. https://localhost:9000) to run it.", caURLEnvVar)
	}

	container = os.Getenv(caContainerEnvVar)
	if container == "" {
		container = defaultCAContainer
	}

	return caURL, container
}

// Requirement: CA-F-04
//
// End-to-end: a real bootstrap token, generated by the real
// Certificate-Authority container, exchanged via NewClient for a real
// client certificate, then used to make a real mTLS-capable HTTPS
// request against that same CA. A successful response proves the
// returned *http.Client is holding a certificate the CA's own root
// trusts — not merely that NewClient returned a non-nil value.
func TestNewClient_RealCA(t *testing.T) {
	caURL, container := skipUnlessCAConfigured(t)
	token := generateTestToken(t, caURL, container, "pki-test-client")

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	client, err := NewClient(ctx, token)
	if err != nil {
		t.Fatalf("NewClient() error = %v, want nil", err)
	}

	healthReq, err := http.NewRequestWithContext(ctx, http.MethodGet, caURL+"/health", nil)
	if err != nil {
		t.Fatalf("http.NewRequestWithContext() error = %v, want nil", err)
	}
	resp, err := client.Do(healthReq)
	if err != nil {
		t.Fatalf("client.Do(%s/health) error = %v, want nil", caURL, err)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		t.Fatalf("client.Do(%s/health) status = %d, want %d", caURL, resp.StatusCode, http.StatusOK)
	}
}

// Requirement: CA-F-04
//
// End-to-end: a real bootstrap token exchanged via NewServer for a real
// server certificate. The certificate is inspected directly (via the
// resulting *tls.Config's GetCertificate, which returns the already
// -obtained certificate from in-memory state, no further network call)
// and confirmed to chain to this dev deployment's own CA name, not merely
// present.
func TestNewServer_RealCA(t *testing.T) {
	caURL, container := skipUnlessCAConfigured(t)
	token := generateTestToken(t, caURL, container, "pki-test-server")

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	server, err := NewServer(ctx, token, &http.Server{Addr: "127.0.0.1:0", ReadHeaderTimeout: 5 * time.Second})
	if err != nil {
		t.Fatalf("NewServer() error = %v, want nil", err)
	}
	if server.TLSConfig == nil {
		t.Fatal("NewServer() TLSConfig = nil, want non-nil")
	}
	if server.TLSConfig.GetCertificate == nil {
		t.Fatal("NewServer() TLSConfig.GetCertificate = nil, want non-nil")
	}

	cert, err := server.TLSConfig.GetCertificate(nil)
	if err != nil {
		t.Fatalf("TLSConfig.GetCertificate(nil) error = %v, want nil", err)
	}
	if len(cert.Certificate) == 0 {
		t.Fatal("GetCertificate() returned a certificate with no DER bytes")
	}

	leaf, err := x509.ParseCertificate(cert.Certificate[0])
	if err != nil {
		t.Fatalf("x509.ParseCertificate(leaf) error = %v, want nil", err)
	}

	found := false
	for _, org := range leaf.Issuer.Organization {
		if org == caName {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("issued certificate's issuer organization = %v, want to contain %q", leaf.Issuer.Organization, caName)
	}
}
